config/routes.rb
Coacheasy::Application.routes.draw do
  devise_for :coaches

  resources :programs
  resources :dashboard
 

  resources :program do
    resources :comments
    resources :comment1s
    resources :comment2s
    resources :comment3s
    resources :comment4s
    resources :comment5s
    resources :comment6s
    get '/print', on: :collection, :controller => 'programs'
  end

  
  match 'home/about.html.erb' => "home#about", :as => :home_about
  match 'home/faq.html.erb' => "home#faq", :as => :home_faq
  match 'home/contact.html.erb' => "home#contact", :as => :home_contact
  

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  

  def initialize(coach)
    can :manage, @program do |program|
      program.coach_id == coach.id
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  
  has_many :programs
  
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :coach, :avatar
  # attr_accessible :title, :body
  has_attached_file :avatar, :styles => { :medium => "150x150>", :thumb => "25x25>" }, :default_url => "/images/:style/missing.png"

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment1.rb
class Comment1 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment2.rb
class Comment2 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment3.rb
class Comment3 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment4.rb
class Comment4 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment5.rb
class Comment5 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment6.rb
class Comment6 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/program.rb
class Program < ActiveRecord::Base
   
  belongs_to :coach
  has_one :comment
  has_one :comment1
  has_one :comment2
  has_one :comment3
  has_one :comment4
  has_one :comment5
  has_one :comment6
  
  validates_presence_of :title
  
  attr_accessible :title, :program_id, :coach_id, :cweekstart, :cweekcomments, :cday1, :cday1zone, :cday2, :cday2zone, :cday3, :cday3zone, :cday4, :cday4zone, :cday5, :cday5zone, :cday6, :cday6zone, :cday7, :cday7zone
  
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'homelayout'
  
  def index
    if coach_signed_in?
       redirect_to :controller => 'dashboard', :action => 'index'
    end
    
  end
  
  def create
    render :layout => 'homelayout'
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  
  before_filter :authenticate_coach!, :except => [:show]
    
  
  # GET /programs
  # GET /programs.json
   
  def index
    @programs = Program.find_all_by_coach_id(current_coach[:id])
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
      format.pdf do
        pdf = ProgramPdf.new(@program, view_context)
        send_data pdf.render, filename: 
        "report_#{@program.title}_#{@program.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf"
      end
    end
    
  end
  
  
  def print
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end
  
  

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])
   
    
    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment1s_helper.rb
module Comment1sHelper
end

app/helpers/comment2s_helper.rb
module Comment2sHelper
end

app/helpers/comment3s_helper.rb
module Comment3sHelper
end

app/helpers/comment4s_helper.rb
module Comment4sHelper
end

app/helpers/comment5s_helper.rb
module Comment5sHelper
end

app/helpers/comment6s_helper.rb
module Comment6sHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name_of_Athlete %><br />
    <%= f.text_field :title %>
    </div>
    
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :cweekstart, :minDate => 0, :maxDate => "+8Y", :size => "8x1" %>
  </div>
  
  <hr />
  
  <div class="field">
    <%= f.label :Comments_for_the_week %><br />
    <%= f.text_area :cweekcomments, :size => "50x5"  %>
  </div>
  
  
  <hr />
  
    
  <div class="field">
    <%= f.label :Day_1_Set_Training %><br />
    <%= f.text_area :cday1, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
	<%= f.select :cday1zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  <div class="field">
    <%= f.label :Day_2_Set_Training %><br />
    <%= f.text_area :cday2, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday2zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  
  <div class="field">
    <%= f.label :Day_3_Set_Training  %><br />
    <%= f.text_area :cday3, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday3zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  
  <div class="field">
    <%= f.label :Day_4_Set_Training  %><br />
    <%= f.text_area :cday4, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday4zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  
  <div class="field">
    <%= f.label :Day_5_Set_Training  %><br />
    <%= f.text_area :cday5, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday5zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  
  <div class="field">
    <%= f.label :Day_6_Set_Training  %><br />
    <%= f.text_area :cday6, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday6zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  <br />
  <br />
  
  
  
  <div class="field">
    <%= f.label :Day_7_Set_Training %><br />
    <%= f.text_area :cday7, :size => "50x5" %>
  </div>
  <div class="field">
    <%= f.label :Training_zone_for_session %><br />
    <%= f.select :cday7zone, [['Z1','Z1'],['Z2','Z2'],['Z3','Z3'],['Z4','Z4'],['Z5','Z5'],['Z6','Z6'],['Z7','Z7']] %>

  </div>
  <br />
  
  
  

  
  
  <%= f.hidden_field :coach_id, :value => current_coach.id %>
  <div class="actions2">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h2>Listing programs</h2>

<table>
	
<% @programs.each do |program| %>
  <tr>
    <td><div style="font-size: 16px; font-weight: bold; text-transform: uppercase;"><%= program.title %> | <%= program.cweekstart %></div></td>
  </tr>
  <tr>
    <td><%= program.cweekcomments %></td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
  </tr>
  <tr>
    <td><div style="font-size: 14px; font-style: oblique;"><%= link_to 'Show', program %> | <%= link_to 'Edit', edit_program_path(program) %></div></td>
    	
    </tr>
  
<% end %>
</table>

<br />
<br />
<br />
<br />

<a href="<%= new_program_path %>"><img src="http://www.iconsdb.com/icons/preview/gray/plus-4-m.png" width="12px" height="12xp" /><b>Add New Program</b></a>

app/views/programs/new.html.erb
<h2>New program</h2>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/print.html.erb
<%= link_to '<< Back', programs_path %> | <a href="mailto:someone@somedomain.com?subject=Your%20Training%20Program%20for%20this%20week&body=<%= request.original_url %>"><img src="http://fbn-i.org/fbn/web.nsf/tiny_email_icon.gif" /> eMail this program to your Athlete </a>
<br /><br />
<h2><%= @program.title %> | <%= @program.cweekstart %></h2>

<hr />
<p>
  <b><i><%= @program.cweekcomments %></i></b>
</p>
<hr />
<br />
<br />













<!-- ##### Coach Program Section 1 - START ##### -->
<%= @program.cday1 %>
<br>
<%= @program.cday1zone %>
<!-- ##### Coach Program Section 1 - END ##### -->
<!-- ##### Athlete Comment Section 1 - START ##### -->

			
    <div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment.other %>
    <br /><br /><br /><br />
  
<!-- ##### Athlete Comment Section 1 - END ##### -->




















<!-- ##### Coach Program Section 2 - START ##### -->
<%= @program.cday2 %>
<br>
<%= @program.cday2zone %>
<!-- ##### Coach Program Section 2 - END ##### -->
<!-- ##### Athlete Comment Section 2 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment1.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment1.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment1.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment1.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment1.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 2 - END ##### -->























<!-- ##### Coach Program Section 3 - START ##### -->
<%= @program.cday3 %>
<br>
<%= @program.cday3zone %>
<!-- ##### Coach Program Section 3 - END ##### -->
<!-- ##### Athlete Comment Section 3 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment2.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment2.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment2.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment2.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment2.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 3 - END ##### -->























<!-- ##### Coach Program Section 4 - START ##### -->
<%= @program.cday4 %>
<br>
<%= @program.cday4zone %>
<!-- ##### Coach Program Section 4 - END ##### -->
<!-- ##### Athlete Comment Section 4 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment3.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment3.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment3.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment3.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment3.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 4 - END ##### -->

























<!-- ##### Coach Program Section 5 - START ##### -->
<%= @program.cday5 %>
<br>
<%= @program.cday5zone %>
<!-- ##### Coach Program Section 5 - END ##### -->
<!-- ##### Athlete Comment Section 5 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment4.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment4.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment4.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment4.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment4.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 5 - END ##### -->

























<!-- ##### Coach Program Section 6 - START ##### -->
<%= @program.cday6 %>
<br>
<%= @program.cday6zone %>
<!-- ##### Coach Program Section 6 - END ##### -->
<!-- ##### Athlete Comment Section 6 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment5.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment5.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment5.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment5.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment5.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 6 - END ##### -->





























<!-- ##### Coach Program Section 7 - START ##### -->
<%= @program.cday7 %>
<br>
<%= @program.cday7zone %>
<!-- ##### Coach Program Section 7 - END ##### -->
<!-- ##### Athlete Comment Section 7 - START ##### -->

<div style="font-weight: bold;">Feedback From Session:</div><br />
    <%= @program.comment6.body %>
    <br /><br />
    <div style="font-weight: bold;">Resting Heart Rate:</div><br />
    <%= @program.comment6.resthr %>
    <br /><br />
    <div style="font-weight: bold;">Training Zone Used:</div><br />
    <%= @program.comment6.tzone %>
    <br /><br />
    <div style="font-weight: bold;">Feel Good Factor:</div><br />
    <%= @program.comment6.fgf %>
    <br /><br />
    <div style="font-weight: bold;">Other Comments:</div><br />
    <%= @program.comment6.other %>
    <br /><br /><br /><br />
    
<!-- ##### Athlete Comment Section 7 - END ##### -->
















<%= link_to '<< Back', programs_path %>