config/routes.rb
Coacheasy::Application.routes.draw do
  devise_for :coaches

  resources :programs
  resources :dashboard
 

  resources :program do
    resources :comments
    resources :comment1s
    resources :comment2s
    resources :comment3s
    resources :comment4s
    resources :comment5s
    resources :comment6s
    get '/print', on: :collection, :controller => 'programs'
  end

  
  match 'home/about.html.erb' => "home#about", :as => :home_about
  match 'home/faq.html.erb' => "home#faq", :as => :home_faq
  match 'home/contact.html.erb' => "home#contact", :as => :home_contact
  

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  

  def initialize(coach)
    can :manage, @program do |program|
      program.coach_id == coach.id
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  
  has_many :programs
  
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :coach, :avatar
  # attr_accessible :title, :body
  has_attached_file :avatar, :styles => { :medium => "150x150>", :thumb => "25x25>" }, :default_url => "/images/:style/missing.png"

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment1.rb
class Comment1 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment2.rb
class Comment2 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment3.rb
class Comment3 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment4.rb
class Comment4 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment5.rb
class Comment5 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/comment6.rb
class Comment6 < ActiveRecord::Base
  
  belongs_to :program
  
  attr_accessible :body, :program_id, :resthr, :tzone, :fgf, :other
end

app/models/program.rb
class Program < ActiveRecord::Base
   
  belongs_to :coach
  has_one :comment
  has_one :comment1
  has_one :comment2
  has_one :comment3
  has_one :comment4
  has_one :comment5
  has_one :comment6
  
  validates_presence_of :title
  
  attr_accessible :title, :program_id, :coach_id, :cweekstart, :cweekcomments, :cday1, :cday1zone, :cday2, :cday2zone, :cday3, :cday3zone, :cday4, :cday4zone, :cday5, :cday5zone, :cday6, :cday6zone, :cday7, :cday7zone
  
  
  
end

app/helpers/comment1s_helper.rb
module Comment1sHelper
end

app/helpers/comment2s_helper.rb
module Comment2sHelper
end

app/helpers/comment3s_helper.rb
module Comment3sHelper
end

app/helpers/comment4s_helper.rb
module Comment4sHelper
end

app/helpers/comment5s_helper.rb
module Comment5sHelper
end

app/helpers/comment6s_helper.rb
module Comment6sHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coacheasy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700|Open+Sans+Condensed:700" rel="stylesheet" />
  <script src="js/jquery.min.js"></script>
  <script src="js/config.js"></script>
  <script src="js/skel.min.js"></script>
  <script src="js/skel-panels.min.js"></script>
  <noscript>
		<link rel="stylesheet" href="css/skel-noscript.css" />
		<link rel="stylesheet" href="css/style.css" />
		<link rel="stylesheet" href="css/style-desktop.css" />
  </noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="css/ie7.css" /><![endif]-->
	
</head>
<body>
	<div class="navbarpro" style="font-family: Arial; font-size: 11pt; padding-top: 5px; padding-bottom: 5px;">
		<center>
		<% if coach_signed_in? %> 
		<a href="<%= dashboard_index_path %>">My Dashboard</a> 
		<% else %> 
		<a href="<%= root_path %>">Home</a>
		<% end %>
		| 
		<a href="<%= home_about_path %>">About us</a>
		| 
		<a href="<%= home_faq_path %>">FAQ</a>
		| 
		<a href="<%= home_contact_path %>">Contact</a>
		</center>
	</div>
	<br />
	<table width="100%">
		<td>
			<div style="font-size: 40px; padding-left: 50px; color: skyblue;" align="left"><b><a href="<%= root_path %>">COACHEASY</a></b></div>
		</td>
		
		
		
		<td>
			<div align="right" style="padding-right: 50px">
		
		<% if coach_signed_in? %>
			<%= image_tag current_coach.avatar.url(:thumb) %> Hello <%= current_coach.firstname%> | <%= link_to 'My Dashboard', dashboard_index_path %> | <%= link_to "Sign out", destroy_coach_session_path, :method => :delete %>
		<% else %>
			<b><%= link_to "Sign up", new_coach_registration_path %></b> or <b><%= link_to "Sign in", new_coach_session_path %></b>
		<% end %>
	</div>
		</td>
	</table>
	<br>
				
		<!-- Main -->
		
			<div id="main-wrapper">
				<div style="background-color: #A9F5BC; width: 100%; font-weight: bold; font-family: Arial, Helvetica, sans-serif; font-size: 10pt;"><center><%= notice %></center></div>
					
				<div id="main" class="container">
							
					<div class="row">
						<div class="12u skel-cell-mainContent">
							<div class="content">
								
							
								<!-- Content -->
						
									<article class="is-page-content">

										<section>
											<p>
												
												<%= yield %>
												
												
											</p>
										</section>
										
										

										

									</article>

								<!-- /Content -->
								
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- /Main -->

		<!-- Footer -->
			<footer id="footer" class="container">
				<div class="row">
					<div class="12u">

						<!-- About -->
							<section>
								<h2 class="major"><span>What's this about?</span></h2>
								<p>
									Coacheasy allows Coaches to communicate with their Athletes. With this application the coach has control and can set weekly programs of whom their Athletes can add feedback and statistics of their set program (including avg heart rate, diet, feel good factor). Currently This website is still in BETA so we would love for you to give feedback on how this could be improved!
								</p>
							</section>
						<!-- /About -->

					</div>
				</div>
				<div class="row">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a href="#facebook" class="facebook">Facebook</a></li>
									<li><a href="#twitter" class="twitter">Twitter</a></li>
									<li><a href="#Linkedin" class="linkedin">LinkedIn</a></li>
									<li><a href="#Googleplus" class="googleplus">Google+</a></li>
								</ul>
							</section>
						<!-- /Contact -->
					
					</div>
				</div>
				
				
					
					<!-- Copyright -->
						<div id="copyright" align="center">
							&copy; 2013 Coacheasy, All rights reservered 
						</div>
					<!-- /Copyright -->
					
				</div>
				
				
			</footer>
		<!-- /Footer -->

	
	





</body>
</html>

app/views/layouts/homelayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coacheasy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700|Open+Sans+Condensed:700" rel="stylesheet" />
  <script src="js/jquery.min.js"></script>
  <script src="js/config.js"></script>
  <script src="js/skel.min.js"></script>
  <script src="js/skel-panels.min.js"></script>
  <noscript>
		<link rel="stylesheet" href="css/skel-noscript.css" />
		<link rel="stylesheet" href="css/style.css" />
		<link rel="stylesheet" href="css/style-desktop.css" />
  </noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="css/ie7.css" /><![endif]-->
	
</head>
<body>
	<div class="navbarpro" style="font-family: Arial; font-size: 11pt; padding-top: 5px; padding-bottom: 5px;">
		<center>
		<% if coach_signed_in? %> 
		<a href="<%= dashboard_index_path %>">My Dashboard</a> 
		<% else %> 
		<a href="<%= root_path %>">Home</a>
		<% end %>
		| 
		<a href="<%= home_about_path %>">About us</a>
		| 
		<a href="<%= home_faq_path %>">FAQ</a>
		| 
		<a href="<%= home_contact_path %>">Contact</a>
		</center>
	</div>
	<br />
	<table width="100%">
		<td>
			<div style="font-size: 40px; padding-left: 50px; font-family: Impact; color: #317082;" align="left"><b><a href="<%= root_path %>">COACH<color = "skyblue">EASY</color></a></b></div>
		</td>
		
		
		
		<td>
			<div align="right" style="padding-right: 50px">
		
		<% if coach_signed_in? %>
			<%= image_tag current_coach.avatar.url(:thumb) %> Hello, <%= current_coach.firstname%> | <%= link_to 'My Dashboard', dashboard_index_path %> | <%= link_to "Sign out", destroy_coach_session_path, :method => :delete %>
		<% else %>
			<b><%= link_to "Sign up", new_coach_registration_path %></b> or <b><%= link_to "Sign in", new_coach_session_path %></b>
		<% end %>
	</div>
		</td>
	</table>
	
	
	
	<br>
								<!-- Content -->
						<div style="background-color: #A9F5BC; width: 100%; font-weight: bold; font-family: Arial, Helvetica, sans-serif; font-size: 10pt;"><center><%= notice %></center></div>
				
									<article class="is-page-content">

										<section>
											<p>
												
												<%= yield %>
												
												
												
											</p>
										</section>
										
										

										

									</article>

								<!-- /Content -->
								
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- /Main -->

		<!-- Footer -->
			<footer id="footer" class="container">
				<div class="row">
					<div class="12u">

						<!-- About -->
							<section>
								<h2 class="major"><span>What's this about?</span></h2>
								<p>
									Coacheasy allows Coaches to communicate with their Athletes. With this application the coach has control and can set weekly programs of whom their Athletes can add feedback and statistics of their set program (including avg heart rate, diet, feel good factor). Currently This website is still in BETA so we would love for you to give feedback on how this could be improved!
								</p>
							</section>
						<!-- /About -->

					</div>
				</div>
				<div class="row">
					<div class="12u">

						<!-- Contact -->
							<section>
								<h2 class="major"><span>Get in touch</span></h2>
								<ul class="contact">
									<li><a href="#facebook" class="facebook">Facebook</a></li>
									<li><a href="#twitter" class="twitter">Twitter</a></li>
									
									<li><a href="#Linkedin" class="linkedin">LinkedIn</a></li>
									<li><a href="#googleplus" class="googleplus">Google+</a></li>
								</ul>
							</section>
						<!-- /Contact -->
					
					</div>
				</div>
				
				
					
					<!-- Copyright -->
						<div id="copyright" align="center">
							&copy; 2013 Coacheasy, All rights reservered 
						</div>
					<!-- /Copyright -->
					
				</div>
				
				
			</footer>
		<!-- /Footer -->

	
	





</body>
</html>